<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ORA Technologies</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styles/omarstyles.css">
</head>

<body class="body">

<header class="animated-bg">
                <div class="top-row">
                    <img src="images/logo.jpg" alt="ORA technologies" class="logo">

                </div>




                <?php include 'nav.inc' ?>

                

</header>