<nav class="menu-nav">
                    <div class="menu">
                        <p class="gradient-text"><a href="index.php">Home</a></p>
                        <p class="gradient-text"><a href="jobs.php">Jobs</a></p>
                        <p class="gradient-text"><a href="apply.php">Apply</a></p>
                        <p class="gradient-text"><a href="about.php">About us</a></p>
                        <p class="gradient-text"><a href="enhancements.php">Enhancements</a></p>
                    </div>
                    <p class="gradient-text email"><a href="mailto:info@ORAtechnologies.com">Email us</a></p>

                    
</nav>